name: Flask CI/CD with Docker

on:
  push:
    branches:
      - main
      - staging
  release:
    types: [created]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest -v

      - name: Build Docker image
        if: success()
        run: |
          IMAGE_NAME=simple-webapp-flask:${{ github.sha }}
          echo "✅ Tests passed. Building Docker image $IMAGE_NAME"
          docker build -t $IMAGE_NAME .

  deploy-staging:
    name: Deploy to Staging
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH & Deploy to Staging Server
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          STAGING_HOST: ${{ secrets.STAGING_HOST }}
          STAGING_USER: ${{ secrets.STAGING_USER }}
        run: |
          echo "$SSH_KEY" > ssh_key && chmod 600 ssh_key

          ssh -o StrictHostKeyChecking=no -i ssh_key $STAGING_USER@$STAGING_HOST << 'EOF'
          set -e

          echo "✅ Bootstrapping server if needed..."
          # Install Docker if missing
          if ! command -v docker &> /dev/null; then
            echo "Installing Docker..."
            sudo apt-get update -y
            sudo apt-get install -y docker.io git
            sudo usermod -aG docker $USER || true
          fi

          # Clone repo if not present
          if [ ! -d "simple-webapp-flask" ]; then
            git clone https://github.com/Kalra-Gunnu/simple-webapp-flask.git
          fi

          cd simple-webapp-flask
          git fetch --all
          git reset --hard origin/staging

          echo "✅ Stopping old container (if exists)"
          sudo docker stop simple-webapp-flask || true
          sudo docker rm simple-webapp-flask || true

          echo "✅ Building Docker image..."
          sudo docker build -t simple-webapp-flask .

          echo "✅ Running new container..."
          sudo docker run -d --name simple-webapp-flask -e APP_ENV=Staging -p 5000:5000 simple-webapp-flask
          EOF

  deploy-production:
    name: Deploy to Production
    needs: build-test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH & Deploy to Production Server
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          PROD_HOST: ${{ secrets.PROD_HOST }}
          PROD_USER: ${{ secrets.PROD_USER }}
        run: |
          echo "$SSH_KEY" > ssh_key && chmod 600 ssh_key

          ssh -o StrictHostKeyChecking=no -i ssh_key $PROD_USER@$PROD_HOST << 'EOF'
          set -e

          echo "✅ Bootstrapping server if needed..."
          # Install Docker if missing
          if ! command -v docker &> /dev/null; then
            echo "Installing Docker..."
            sudo apt-get update -y
            sudo apt-get install -y docker.io git
            sudo usermod -aG docker $USER || true
          fi

          # Clone repo if not present
          if [ ! -d "simple-webapp-flask" ]; then
            git clone https://github.com/Kalra-Gunnu/simple-webapp-flask.git
          fi

          cd simple-webapp-flask
          git fetch --all
          git reset --hard origin/main

          echo "✅ Stopping old container (if exists)"
          sudo docker stop simple-webapp-flask || true
          sudo docker rm simple-webapp-flask || true

          echo "✅ Building Docker image..."
          sudo docker build -t simple-webapp-flask .

          echo "✅ Running new container..."
          sudo docker run -d --name simple-webapp-flask -e APP_ENV=Production -p 5000:5000 simple-webapp-flask
          EOF
